# https://pnpm.io/continuous-integration#github-actions
name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - production

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
      # TODO run e2e test here
      - name: Build
        run: pnpm build
      - name: Deploy to development
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER: ${{secrets.SSH_USER}}
        run: |
          echo "Deploying to server uat..."
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOSTNAME} 'bash -s' < ./deploy.sh
      - name: Deploy to production
        if: github.ref == 'refs/heads/production'
        env:
          PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_PRODUCTION}}
          HOSTNAME: ${{secrets.SSH_HOST_PRODUCTION}}
          USER: ${{secrets.SSH_USER_PRODUCTION}}
        run: |
          echo "Deploying to server production..."
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOSTNAME} 'bash -s' < ./deploy.sh
