name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER: ${{secrets.SSH_USER}}

        # run: |
        #   echo "Deploying application..."
        #   echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        #   ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOSTNAME} '
        #       cd ./github-action &&
        #       git checkout main &&
        #       git fetch --all &&
        #       git reset --hard origin/main &&
        #       git pull origin main &&
        #       # Run deploy script ./production.sh
        #       touch deleteme
        #       '

        run: |
          echo "Deploying application..."
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOSTNAME} 'bash -s' < ./deploy.sh
